# Generated by Django 6.0.6 on 2026-08-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='external_image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
